'use strict';

// SIID 4 — Vacuum Extend (core cleaning properties)

module.exports = {
  statusStates: [
    {
      id: 'status',
      siid: 4,
      piid: 1,
      nameKey: 'vacuum.status.status',
      type: 'number',
      role: 'value',
      states: {
        0: 'Idle',
        1: 'Paused',
        2: 'Cleaning',
        3: 'Back home',
        4: 'Part cleaning',
        5: 'Follow wall',
        6: 'Charging',
        7: 'OTA',
        10: 'Power off',
        12: 'Error',
        13: 'Remote control',
        14: 'Sleeping',
        17: 'Standby',
        18: 'Segment cleaning',
        19: 'Zone cleaning',
        20: 'Spot cleaning',
        21: 'Fast mapping',
        22: 'Cruising path',
        23: 'Cruising point',
        24: 'Summon clean',
        25: 'Shortcut',
        26: 'Person follow',
      },
    },
    {
      id: 'cleaning-time',
      siid: 4,
      piid: 2,
      nameKey: 'vacuum.status.cleaning-time',
      type: 'number',
      role: 'value',
      unit: 'min',
    },
    {
      id: 'cleaned-area',
      siid: 4,
      piid: 3,
      nameKey: 'vacuum.status.cleaned-area',
      type: 'number',
      role: 'value',
      unit: 'm²',
    },
    {
      id: 'water-tank',
      siid: 4,
      piid: 6,
      nameKey: 'vacuum.status.water-tank',
      type: 'number',
      role: 'value',
      states: { 0: 'Not installed', 1: 'Installed', 10: 'Mop installed' },
    },
    {
      id: 'task-status',
      siid: 4,
      piid: 7,
      nameKey: 'vacuum.status.task-status',
      type: 'number',
      role: 'value',
      states: {
        0: 'Completed',
        1: 'Auto cleaning',
        2: 'Zone cleaning',
        3: 'Segment cleaning',
        4: 'Spot cleaning',
        5: 'Fast mapping',
        6: 'Auto paused',
        7: 'Zone paused',
        8: 'Segment paused',
        9: 'Spot paused',
      },
    },
    { id: 'serial-number',           siid: 4, piid: 14, nameKey: 'vacuum.status.serial-number',          type: 'string', role: 'text' },
    { id: 'mop-cleaning-remainder',  siid: 4, piid: 16, nameKey: 'vacuum.status.mop-cleaning-remainder',  type: 'number', role: 'value' },
    { id: 'cleaning-paused',         siid: 4, piid: 17, nameKey: 'vacuum.status.cleaning-paused',         type: 'number', role: 'value' },
    { id: 'faults',                  siid: 4, piid: 18, nameKey: 'vacuum.status.faults',                  type: 'string', role: 'text' },
    { id: 'nation-matched',          siid: 4, piid: 19, nameKey: 'vacuum.status.nation-matched',          type: 'string', role: 'text' },
    { id: 'relocation-status',       siid: 4, piid: 20, nameKey: 'vacuum.status.relocation-status',       type: 'number', role: 'value' },
    { id: 'self-wash-base-status',   siid: 4, piid: 25, nameKey: 'vacuum.status.self-wash-base-status',   type: 'number', role: 'value' },
    { id: 'upload-map',              siid: 4, piid: 24, nameKey: 'vacuum.status.upload-map',              type: 'number', role: 'value' },
    { id: 'warn-status',             siid: 4, piid: 35, nameKey: 'vacuum.status.warn-status',             type: 'number', role: 'value' },
    { id: 'low-water-warning',       siid: 4, piid: 41, nameKey: 'vacuum.status.low-water-warning',       type: 'number', role: 'value' },
    { id: 'scheduled-clean',         siid: 4, piid: 47, nameKey: 'vacuum.status.scheduled-clean',        type: 'number', role: 'value' },
    { id: 'shortcuts',               siid: 4, piid: 48, nameKey: 'vacuum.status.shortcuts',               type: 'string', role: 'json' },
    { id: 'intelligent-recognition', siid: 4, piid: 49, nameKey: 'vacuum.status.intelligent-recognition', type: 'number', role: 'value' },
    { id: 'auto-switch-settings',    siid: 4, piid: 50, nameKey: 'vacuum.status.auto-switch-settings',    type: 'string', role: 'json' },
    { id: 'mop-in-station',          siid: 4, piid: 52, nameKey: 'vacuum.status.mop-in-station',          type: 'number', role: 'value' },
    { id: 'mop-pad-installed',       siid: 4, piid: 53, nameKey: 'vacuum.status.mop-pad-installed',       type: 'number', role: 'value' },
    { id: 'task-type',               siid: 4, piid: 58, nameKey: 'vacuum.status.task-type',               type: 'number', role: 'value' },
    { id: 'drainage-status',         siid: 4, piid: 60, nameKey: 'vacuum.status.drainage-status',         type: 'number', role: 'value' },
    { id: 'cleaning-progress',       siid: 4, piid: 63, nameKey: 'vacuum.status.cleaning-progress',       type: 'number', role: 'value', unit: '%' },
    { id: 'drying-progress',         siid: 4, piid: 64, nameKey: 'vacuum.status.drying-progress',         type: 'number', role: 'value', unit: '%' },
    { id: 'device-capability',       siid: 4, piid: 83, nameKey: 'vacuum.status.device-capability',       type: 'number', role: 'value' },
  ],

  remoteStates: [
    {
      id: 'suction-level',
      siid: 4,
      piid: 4,
      nameKey: 'vacuum.remote.suction-level',
      type: 'number',
      role: 'level',
      states: { 0: 'Quiet', 1: 'Standard', 2: 'Strong', 3: 'Turbo' },
    },
    {
      id: 'water-volume',
      siid: 4,
      piid: 5,
      nameKey: 'vacuum.remote.water-volume',
      type: 'number',
      role: 'level',
      states: { 1: 'Low', 2: 'Medium', 3: 'High' },
    },
    {
      id: 'cleaning-mode',
      siid: 4,
      piid: 23,
      nameKey: 'vacuum.remote.cleaning-mode',
      type: 'number',
      role: 'level',
      states: { 0: 'Sweeping', 1: 'Mopping', 2: 'Sweep+Mop', 3: 'Mop after sweep' },
    },
    { id: 'resume-cleaning',    siid: 4, piid: 11, nameKey: 'vacuum.remote.resume-cleaning',    type: 'boolean', role: 'switch' },
    { id: 'carpet-boost',       siid: 4, piid: 12, nameKey: 'vacuum.remote.carpet-boost',       type: 'boolean', role: 'switch' },
    { id: 'obstacle-avoidance', siid: 4, piid: 21, nameKey: 'vacuum.remote.obstacle-avoidance', type: 'boolean', role: 'switch' },
    { id: 'ai-detection',       siid: 4, piid: 22, nameKey: 'vacuum.remote.ai-detection',       type: 'number',  role: 'level', write: false },
    { id: 'customized-cleaning',siid: 4, piid: 26, nameKey: 'vacuum.remote.customized-cleaning',type: 'boolean', role: 'switch' },
    { id: 'child-lock',         siid: 4, piid: 27, nameKey: 'vacuum.remote.child-lock',         type: 'boolean', role: 'switch' },
    {
      id: 'carpet-sensitivity',
      siid: 4,
      piid: 28,
      nameKey: 'vacuum.remote.carpet-sensitivity',
      type: 'number',
      role: 'level',
      states: { 1: 'Low', 2: 'Medium', 3: 'High' },
    },
    { id: 'tight-mopping',      siid: 4, piid: 29, nameKey: 'vacuum.remote.tight-mopping',      type: 'boolean', role: 'switch' },
    { id: 'carpet-recognition', siid: 4, piid: 33, nameKey: 'vacuum.remote.carpet-recognition', type: 'boolean', role: 'switch' },
    { id: 'self-clean',         siid: 4, piid: 34, nameKey: 'vacuum.remote.self-clean',         type: 'boolean', role: 'switch' },
    {
      id: 'carpet-cleaning',
      siid: 4,
      piid: 36,
      nameKey: 'vacuum.remote.carpet-cleaning',
      type: 'number',
      role: 'level',
      states: { 0: 'Avoid', 1: 'Adapt', 2: 'Ignore' },
    },
    { id: 'auto-add-detergent',  siid: 4, piid: 37, nameKey: 'vacuum.remote.auto-add-detergent',  type: 'boolean', role: 'switch' },
    {
      id: 'drying-time',
      siid: 4,
      piid: 40,
      nameKey: 'vacuum.remote.drying-time',
      type: 'number',
      role: 'level',
      states: { 2: '2h', 3: '3h', 4: '4h' },
    },
    { id: 'auto-mount-mop',      siid: 4, piid: 45, nameKey: 'vacuum.remote.auto-mount-mop',      type: 'boolean', role: 'switch' },
    { id: 'mop-wash-level',      siid: 4, piid: 46, nameKey: 'vacuum.remote.mop-wash-level',      type: 'number',  role: 'level' },
    { id: 'auto-water-refilling',siid: 4, piid: 51, nameKey: 'vacuum.remote.auto-water-refilling',type: 'boolean', role: 'switch' },
  ],
};
