'use strict';

// SIID 2 — Robot Cleaner (state, error)
// SIID 3 — Battery

const VACUUM_ROBOT_STATES = {
  1: 'Cleaning',
  2: 'Standby',
  3: 'Paused',
  4: 'Paused',
  5: 'Returning to charge',
  6: 'Charging',
  7: 'Mopping',
  8: 'Mop Drying',
  9: 'Mop Washing',
  10: 'Returning to wash',
  11: 'Mapping',
  12: 'Cleaning',
  13: 'Charging Completed',
  14: 'Upgrading',
  15: 'Summon to clean',
  16: 'Self-Repairing',
  17: 'Returning to install the mop pad',
  18: 'Returning to remove the mop pad',
  19: 'Automatic water supply and drainage self testing',
  20: 'Cleaning Mop Pad and Adding Water',
  21: 'Cleaning paused',
  22: 'Auto-Emptying',
  23: 'Remote Controlled Cleaning',
  24: 'Smart Charging',
  25: 'Second cleaning underway',
  26: 'Following',
  27: 'Spot cleaning',
  28: 'Returning for dust collection',
  29: 'Waiting for tasks',
  30: 'Cleaning the washboard base',
  31: 'Returning to drain',
  32: 'Draining',
  33: 'Water Supply and Drainage Emptying',
  34: 'Emptying',
  35: 'Dust bag drying',
  36: 'Dust bag drying paused',
  37: 'Heading to extra cleaning',
  38: 'Extra cleaning',
  95: 'Finding pet paused',
  96: 'Finding pet',
  97: 'Shortcut running',
  98: 'Camera Monitoring',
  99: 'Camera monitoring paused',
  101: 'Initial deep cleaning',
  102: 'Initial deep cleaning paused',
  103: 'Sanitizing',
  104: 'Sanitizing with dry',
  105: 'Changing mop',
  106: 'Changing mop paused',
  107: 'Floor maintaining',
  108: 'Floor maintaining paused',
};

module.exports = {
  statusStates: [
    // SIID 2 — Robot Cleaner
    {
      id: 'state',
      siid: 2,
      piid: 1,
      nameKey: 'vacuum.status.state',
      type: 'number',
      role: 'value',
      states: VACUUM_ROBOT_STATES,
    },
    {
      id: 'error',
      siid: 2,
      piid: 2,
      nameKey: 'vacuum.status.error',
      type: 'number',
      role: 'value',
    },
    // SIID 3 — Battery
    {
      id: 'battery-level',
      siid: 3,
      piid: 1,
      nameKey: 'vacuum.status.battery-level',
      type: 'number',
      role: 'value.battery',
      unit: '%',
    },
    {
      id: 'charging-status',
      siid: 3,
      piid: 2,
      nameKey: 'vacuum.status.charging-status',
      type: 'number',
      role: 'value',
      states: { 1: 'Charging', 2: 'Not charging', 3: 'Charging completed', 5: 'Return to charge' },
    },
    {
      id: 'off-peak-charging',
      siid: 3,
      piid: 3,
      nameKey: 'vacuum.status.off-peak-charging',
      type: 'string',
      role: 'json',
    },
  ],
  remoteStates: [],
};
