'use strict';

// SIID 2 — Robot Cleaner (state, error)
// SIID 3 — Battery

// stateKeys: 1/12 → common.cleaning, 3/4 → common.paused, 6 → common.charging, 13 → common.charging-completed
const VACUUM_ROBOT_STATE_KEYS = {
  1:   'common.cleaning',
  2:   'vacuum.state.standby',
  3:   'common.paused',
  4:   'common.paused',
  5:   'vacuum.state.returning-to-charge',
  6:   'common.charging',
  7:   'vacuum.state.mopping',
  8:   'vacuum.state.mop-drying',
  9:   'vacuum.state.mop-washing',
  10:  'vacuum.state.returning-to-wash',
  11:  'vacuum.state.mapping',
  12:  'common.cleaning',
  13:  'common.charging-completed',
  14:  'vacuum.state.upgrading',
  15:  'vacuum.state.summon-to-clean',
  16:  'vacuum.state.self-repairing',
  17:  'vacuum.state.returning-to-install-mop-pad',
  18:  'vacuum.state.returning-to-remove-mop-pad',
  19:  'vacuum.state.auto-water-drainage-test',
  20:  'vacuum.state.cleaning-mop-pad-adding-water',
  21:  'vacuum.state.cleaning-paused',
  22:  'vacuum.state.auto-emptying',
  23:  'vacuum.state.remote-controlled-cleaning',
  24:  'vacuum.state.smart-charging',
  25:  'vacuum.state.second-cleaning',
  26:  'vacuum.state.following',
  27:  'vacuum.state.spot-cleaning',
  28:  'vacuum.state.returning-for-dust-collection',
  29:  'vacuum.state.waiting-for-tasks',
  30:  'vacuum.state.cleaning-washboard-base',
  31:  'vacuum.state.returning-to-drain',
  32:  'vacuum.state.draining',
  33:  'vacuum.state.water-drainage-emptying',
  34:  'vacuum.state.emptying',
  35:  'vacuum.state.dust-bag-drying',
  36:  'vacuum.state.dust-bag-drying-paused',
  37:  'vacuum.state.heading-to-extra-cleaning',
  38:  'vacuum.state.extra-cleaning',
  95:  'vacuum.state.finding-pet-paused',
  96:  'vacuum.state.finding-pet',
  97:  'vacuum.state.shortcut-running',
  98:  'vacuum.state.camera-monitoring',
  99:  'vacuum.state.camera-monitoring-paused',
  101: 'vacuum.state.initial-deep-cleaning',
  102: 'vacuum.state.initial-deep-cleaning-paused',
  103: 'vacuum.state.sanitizing',
  104: 'vacuum.state.sanitizing-with-dry',
  105: 'vacuum.state.changing-mop',
  106: 'vacuum.state.changing-mop-paused',
  107: 'vacuum.state.floor-maintaining',
  108: 'vacuum.state.floor-maintaining-paused',
};

// Error codes (2-2). Cross-verified against two independent MIT projects decoding the same
// MIoT property: spayrosam/ioBroker.dreamehome (98 codes) and Tasshack/dreame-vacuum (87) —
// 86 overlapping codes, no contradictions.
const VACUUM_ERROR_KEYS = {
  '-1': 'vacuum.error.unknown',
  0:    'vacuum.error.no-error',
  1:    'vacuum.error.drop',
  2:    'vacuum.error.cliff',
  3:    'vacuum.error.bumper',
  4:    'vacuum.error.gesture',
  5:    'vacuum.error.bumper-repeat',
  6:    'vacuum.error.drop-repeat',
  7:    'vacuum.error.optical-flow',
  8:    'vacuum.error.box',
  9:    'vacuum.error.tankbox',
  10:   'vacuum.error.waterbox-empty',
  11:   'vacuum.error.box-full',
  12:   'vacuum.error.brush',
  13:   'vacuum.error.side-brush',
  14:   'vacuum.error.fan',
  15:   'vacuum.error.left-wheel-motor',
  16:   'vacuum.error.right-wheel-motor',
  17:   'vacuum.error.turn-suffocate',
  18:   'vacuum.error.forward-suffocate',
  19:   'vacuum.error.charger-get',
  20:   'vacuum.error.battery-low',
  21:   'vacuum.error.charge-fault',
  22:   'vacuum.error.battery-percentage',
  23:   'vacuum.error.heart',
  24:   'vacuum.error.camera-occlusion',
  25:   'vacuum.error.move',
  26:   'vacuum.error.flow-shielding',
  27:   'vacuum.error.infrared-shielding',
  28:   'vacuum.error.charge-no-electric',
  29:   'vacuum.error.battery-fault',
  30:   'vacuum.error.fan-speed-error',
  31:   'vacuum.error.left-wheel-speed',
  32:   'vacuum.error.right-wheel-speed',
  33:   'vacuum.error.bmi055-acce',
  34:   'vacuum.error.bmi055-gyro',
  35:   'vacuum.error.xv7001',
  36:   'vacuum.error.left-magnet',
  37:   'vacuum.error.right-magnet',
  38:   'vacuum.error.flow-error',
  39:   'vacuum.error.infrared-fault',
  40:   'vacuum.error.camera-fault',
  41:   'vacuum.error.strong-magnet',
  42:   'vacuum.error.water-pump',
  43:   'vacuum.error.rtc',
  44:   'vacuum.error.auto-key-trig',
  45:   'vacuum.error.p3v3',
  46:   'vacuum.error.camera-idle',
  47:   'vacuum.error.blocked',
  48:   'vacuum.error.lds-error',
  49:   'vacuum.error.lds-bumper',
  50:   'vacuum.error.water-pump-2',
  51:   'vacuum.error.filter-blocked',
  54:   'vacuum.error.edge',
  55:   'vacuum.error.carpet',
  56:   'vacuum.error.laser',
  57:   'vacuum.error.edge-2',
  58:   'vacuum.error.ultrasonic',
  59:   'vacuum.error.no-go-zone',
  61:   'vacuum.error.route',
  62:   'vacuum.error.route-2',
  63:   'vacuum.error.blocked-2',
  64:   'vacuum.error.blocked-3',
  65:   'vacuum.error.restricted',
  66:   'vacuum.error.restricted-2',
  67:   'vacuum.error.restricted-3',
  68:   'vacuum.error.remove-mop',
  69:   'vacuum.error.mop-removed',
  70:   'vacuum.error.mop-removed-2',
  71:   'vacuum.error.mop-pad-stop-rotate',
  72:   'vacuum.error.mop-pad-stop-rotate-2',
  74:   'vacuum.error.mop-install-failed',
  75:   'vacuum.error.low-battery-turn-off',
  76:   'vacuum.error.dirty-tank-not-installed',
  78:   'vacuum.error.robot-in-hidden-room',
  101:  'vacuum.error.bin-full',
  102:  'vacuum.error.bin-open',
  103:  'vacuum.error.bin-open-2',
  104:  'vacuum.error.bin-full-2',
  105:  'vacuum.error.water-tank',
  106:  'vacuum.error.dirty-water-tank',
  107:  'vacuum.error.water-tank-dry',
  108:  'vacuum.error.dirty-water-tank-2',
  109:  'vacuum.error.dirty-water-tank-blocked',
  110:  'vacuum.error.dirty-water-tank-pump',
  111:  'vacuum.error.mop-pad',
  112:  'vacuum.error.wet-mop-pad',
  114:  'vacuum.error.clean-mop-pad',
  116:  'vacuum.error.clean-tank-level',
  117:  'vacuum.error.station-disconnected',
  118:  'vacuum.error.dirty-tank-level',
  119:  'vacuum.error.washboard-level',
  120:  'vacuum.error.no-mop-in-station',
  121:  'vacuum.error.dust-bag-full',
  122:  'vacuum.error.unknown-warning-2',
  123:  'vacuum.error.self-test-failed',
  124:  'vacuum.error.washboard-not-working',
  1000: 'vacuum.error.return-to-charge-failed',
};

module.exports = {
  statusStates: [
    // SIID 2 — Robot Cleaner
    {
      id: 'state',
      siid: 2,
      piid: 1,
      nameKey: 'vacuum.status.state',
      type: 'number',
      role: 'value',
      stateKeys: VACUUM_ROBOT_STATE_KEYS,
    },
    {
      id: 'error',
      siid: 2,
      piid: 2,
      nameKey: 'vacuum.status.error',
      type: 'number',
      role: 'value',
      stateKeys: VACUUM_ERROR_KEYS,
    },
    // SIID 3 — Battery
    {
      id: 'battery-level',
      siid: 3,
      piid: 1,
      nameKey: 'vacuum.status.battery-level',
      type: 'number',
      role: 'value.battery',
      unit: '%',
    },
    {
      id: 'charging-status',
      siid: 3,
      piid: 2,
      nameKey: 'vacuum.status.charging-status',
      type: 'number',
      role: 'value',
      stateKeys: { 1: 'common.charging', 2: 'common.not-charging', 3: 'common.charging-completed', 5: 'vacuum.charging-status.return-to-charge' },
    },
    {
      id: 'off-peak-charging',
      siid: 3,
      piid: 3,
      nameKey: 'vacuum.status.off-peak-charging',
      type: 'string',
      role: 'json',
    },
    // SIID 2 PIID 6: device pushes this property (seen in real MQTT traffic,
    // value:1 in known example). Exact meaning unknown — registered to prevent
    // generic fallback state. Name will be clarified once meaning is confirmed.
    {
      id: 'robot-cleaner-2-6',
      siid: 2,
      piid: 6,
      nameKey: 'vacuum.status.robot-cleaner-2-6',
      type: 'number',
      role: 'value',
    },
  ],
  remoteStates: [],
};
