'use strict';

// SIID 2 — Robot Cleaner (state, error)
// SIID 3 — Battery
// SIID 99 — Device Info (firmware / MCU version)

// stateKeys: 1/12 → common.cleaning, 3/4 → common.paused, 6 → common.charging, 13 → common.charging-completed
const VACUUM_ROBOT_STATE_KEYS = {
  1:   'common.cleaning',
  2:   'vacuum.state.standby',
  3:   'common.paused',
  4:   'common.paused',
  5:   'vacuum.state.returning-to-charge',
  6:   'common.charging',
  7:   'vacuum.state.mopping',
  8:   'vacuum.state.mop-drying',
  9:   'vacuum.state.mop-washing',
  10:  'vacuum.state.returning-to-wash',
  11:  'vacuum.state.mapping',
  12:  'common.cleaning',
  13:  'common.charging-completed',
  14:  'vacuum.state.upgrading',
  15:  'vacuum.state.summon-to-clean',
  16:  'vacuum.state.self-repairing',
  17:  'vacuum.state.returning-to-install-mop-pad',
  18:  'vacuum.state.returning-to-remove-mop-pad',
  19:  'vacuum.state.auto-water-drainage-test',
  20:  'vacuum.state.cleaning-mop-pad-adding-water',
  21:  'vacuum.state.cleaning-paused',
  22:  'vacuum.state.auto-emptying',
  23:  'vacuum.state.remote-controlled-cleaning',
  24:  'vacuum.state.smart-charging',
  25:  'vacuum.state.second-cleaning',
  26:  'vacuum.state.following',
  27:  'vacuum.state.spot-cleaning',
  28:  'vacuum.state.returning-for-dust-collection',
  29:  'vacuum.state.waiting-for-tasks',
  30:  'vacuum.state.cleaning-washboard-base',
  31:  'vacuum.state.returning-to-drain',
  32:  'vacuum.state.draining',
  33:  'vacuum.state.water-drainage-emptying',
  34:  'vacuum.state.emptying',
  35:  'vacuum.state.dust-bag-drying',
  36:  'vacuum.state.dust-bag-drying-paused',
  37:  'vacuum.state.heading-to-extra-cleaning',
  38:  'vacuum.state.extra-cleaning',
  95:  'vacuum.state.finding-pet-paused',
  96:  'vacuum.state.finding-pet',
  97:  'vacuum.state.shortcut-running',
  98:  'vacuum.state.camera-monitoring',
  99:  'vacuum.state.camera-monitoring-paused',
  101: 'vacuum.state.initial-deep-cleaning',
  102: 'vacuum.state.initial-deep-cleaning-paused',
  103: 'vacuum.state.sanitizing',
  104: 'vacuum.state.sanitizing-with-dry',
  105: 'vacuum.state.changing-mop',
  106: 'vacuum.state.changing-mop-paused',
  107: 'vacuum.state.floor-maintaining',
  108: 'vacuum.state.floor-maintaining-paused',
};

module.exports = {
  statusStates: [
    // SIID 2 — Robot Cleaner
    {
      id: 'state',
      siid: 2,
      piid: 1,
      nameKey: 'vacuum.status.state',
      type: 'number',
      role: 'value',
      stateKeys: VACUUM_ROBOT_STATE_KEYS,
    },
    {
      id: 'error',
      siid: 2,
      piid: 2,
      nameKey: 'vacuum.status.error',
      type: 'number',
      role: 'value',
    },
    // SIID 3 — Battery
    {
      id: 'battery-level',
      siid: 3,
      piid: 1,
      nameKey: 'vacuum.status.battery-level',
      type: 'number',
      role: 'value.battery',
      unit: '%',
    },
    {
      id: 'charging-status',
      siid: 3,
      piid: 2,
      nameKey: 'vacuum.status.charging-status',
      type: 'number',
      role: 'value',
      stateKeys: { 1: 'common.charging', 2: 'common.not-charging', 3: 'common.charging-completed', 5: 'vacuum.charging-status.return-to-charge' },
    },
    {
      id: 'off-peak-charging',
      siid: 3,
      piid: 3,
      nameKey: 'vacuum.status.off-peak-charging',
      type: 'string',
      role: 'json',
    },
    // SIID 2 PIID 6: device pushes this property (seen in real MQTT traffic,
    // value:1 in known example). Exact meaning unknown — registered to prevent
    // generic fallback state. Name will be clarified once meaning is confirmed.
    {
      id: 'robot-cleaner-2-6',
      siid: 2,
      piid: 6,
      nameKey: 'vacuum.status.robot-cleaner-2-6',
      type: 'number',
      role: 'value',
    },
    // SIID 99 — Device Info (firmware)
    { id: 'firmware-version', siid: 99, piid: 17, nameKey: 'vacuum.status.firmware-version', type: 'string', role: 'text' },
    { id: 'mcu-version',      siid: 99, piid: 31, nameKey: 'vacuum.status.mcu-version',      type: 'string', role: 'json' },
  ],
  remoteStates: [],
};
